# Uncomment the next line to define a global platform for your project
# platform :ios, '16.0'

target 'ContactManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  #Alamofire
  pod 'Alamofire'

 #Kingfisher
  pod 'Kingfisher'

end
